;; Common tools and face assignment table for Tao Yin & Yang

(require 'cl-lib)

(defun tao-theme-golden-grayscale ()
  "Generate a golden mean based greyscale gradient."
  (let (zeta
        (phi (/ (+ 1 (sqrt 5)) 2)))
    (dotimes (n 7)
      (let* ((delta (/ #xFF (expt phi (+ 2 n))))
             (gamma (- #xFF delta)))
             (push (format "#%02X%02X%02X" delta delta delta) zeta)
             (setq zeta (append zeta (list (format "#%02X%02X%02X" gamma gamma gamma))))
             ))
    zeta))

(defun tao-theme-golden-grayscale-yang-palette ()
  "Generate a light version of the golden gradient alist."
  (cl-loop for value in '(8 10 9 11 8 7 6 5 4 3 2 1 1 1)
           count value into index
           collect (cons (concat "color-" (format "%d" index))
                         (nth value (tao-theme-golden-grayscale)))))

(defun tao-theme-golden-grayscale-yin-palette ()
  "Generate a dark version of the golden gradient alist."
  (cl-loop for value in (tao-theme-golden-grayscale)
           count value into index
           collect (cons (concat "color-" (format "%d" index)) value)))

(defmacro tao-with-color-variables (tao-colors &rest body)
  "`let' bind all colors defined in TAO-COLORS around BODY.
Also bind `class' to ((class color) (min-colors 89))."
  (declare (indent 0))
  `(let ((class '((class color) (min-colors 89)))
         ,@(mapcar (lambda (c)
                     (list (intern (car c)) (cdr c)))
                   (funcall tao-colors)))
     ,@body))

(defun tao-apply-custom-theme (theme-name)
  (custom-theme-set-faces
   theme-name
   ;; Built-in
   `(button                                           ((t (:underline t))))
   `(link ((t (:foreground "#517FA6" :underline t))))
   `(link-visited                                     ((t (:foreground ,color-11 :underline t :weight normal))))
   `(default                                          ((t (:foreground ,color-9 :background ,color-4))))
   `(hl-paren-face                                    ((t (:foreground ,color-12 :background ,color-3 :wight bold))))
   `(cursor                                           ((t (:foreground ,color-13 :background ,color-14))))
   `(escape-glyph                                     ((t (:foreground ,color-13 :bold t))))
   `(fringe                                           ((t (:foreground ,color-2 :background ,color-4))))
   `(header-line                                      ((t (:inherit mode-line))))
   `(highlight                                        ((t (:background ,color-4))))
   `(success                                          ((t (:foreground ,color-9 :weight bold))))
   `(warning                                          ((t (:foreground ,color-11 :weight bold))))
   ;; compilation
   `(compilation-column-face                          ((t (:foreground ,color-13))))
   `(compilation-enter-directory-face                 ((t (:foreground ,color-9))))
   `(compilation-error-face                           ((t (:foreground ,color-9 :weight bold :underline t))))
   `(compilation-face                                 ((t (:foreground ,color-13))))
   `(compilation-info-face                            ((t (:foreground ,color-11))))
   `(compilation-info                                 ((t (:foreground ,color-13 :underline t))))
   `(compilation-leave-directory-face                 ((t (:foreground ,color-9))))
   `(compilation-line-face                            ((t (:foreground ,color-13))))
   `(compilation-line-number                          ((t (:foreground ,color-13))))
   `(compilation-message-face                         ((t (:foreground ,color-11))))
   `(compilation-warning-face                         ((t (:foreground ,color-11 :weight bold :underline t))))
   `(compilation-mode-line-exit                       ((t (:foreground ,color-11 :weight bold))))
   `(compilation-mode-line-fail                       ((t (:foreground ,color-10 :weight bold))))
   `(compilation-mode-line-run                        ((t (:foreground ,color-13 :weight bold))))
   ;; grep
   `(grep-context-face                                ((t (:foreground ,color-13))))
   `(grep-error-face                                  ((t (:foreground ,color-9 :weight bold :underline t))))
   `(grep-hit-face                                    ((t (:foreground ,color-11))))
   `(grep-match-face                                  ((t (:foreground ,color-11 :weight bold))))
   `(match                                            ((t (:background ,color-3 :foreground ,color-11 :weight bold))))
   ;; make
   `(makefile-space                                   ((t (:background ,color-4))))
   `(makefile-targets                                   ((t (:underline t))))
   `(makefile-shell                                   ((t (:slant italic))))
   ;; isearch
   `(isearch                                          ((t (:foreground ,color-11 :weight bold :background ,color-6))))
   `(isearch-fail                                     ((t (:foreground ,color-13 :background ,color-7))))
   `(lazy-highlight                                   ((t (:foreground ,color-11 :weight bold :background ,color-5))))
   `(menu                                             ((t (:foreground ,color-13 :background ,color-4))))
   `(minibuffer-prompt                                ((t (:foreground ,color-13 :color ,color-1))))
   `(mode-line                                        ((,class (:foreground ,color-2 :background ,color-8 :box nil )) (t :inverse-video t)))
   `(mode-line-inactive                               ((t (:foreground ,color-3 :background ,color-6 :box nil))))
   `(mode-line-buffer-id                              ((t (:foreground ,color-4 :weight bold))))
   `(region                                           ((,class (:background ,color-9 :foreground ,color-3)) (t :inverse-video t)))
   `(secondary-selection                              ((t (:background ,color-4))))
   `(cua-rectangle                                    ((t (:background ,color-4))))
   `(trailing-whitespace                              ((t (:background ,color-10))))
   `(vertical-border                                  ((t (:foreground ,color-7 :background ,color-4))))
   ;; font lock
   `(font-lock-builtin-face                           ((t (:foreground ,color-13 :weight bold))))
   `(font-lock-comment-face                           ((t (:foreground ,color-7 :weight bold))))
   `(font-lock-comment-delimiter-face                 ((t (:foreground ,color-8))))
   `(font-lock-constant-face                          ((t (:foreground ,color-8 :weight bold))))
   `(font-lock-doc-face                               ((t (:foreground ,color-7))))
   `(font-lock-function-name-face                     ((t (:foreground "#517FA6" :weight bold))))
   `(font-lock-keyword-face                           ((t (:foreground ,color-13))))
   `(font-lock-negation-char-face                     ((t (:foreground ,color-13 :weight bold))))
   `(font-lock-preprocessor-face                      ((t (:foreground ,color-11))))
   `(font-lock-regexp-grouping-construct              ((t (:foreground ,color-13 :weight bold))))
   `(font-lock-regexp-grouping-backslash              ((t (:foreground ,color-9 :weight bold))))
   `(font-lock-string-face                            ((t (:foreground ,color-8 :slant oblique))))
   `(font-lock-type-face                              ((t (:foreground ,color-10))))
   `(font-lock-variable-name-face                     ((t (:foreground ,color-14))))
   `(font-lock-warning-face                           ((t (:foreground ,color-11 :weight bold))))
   ;; highlight-symbol
   `(highlight-symbol-face                            ((t (:background ,color-4) )))
   ;; ace-jump
   `(ace-jump-face-background                         ((t (:foreground ,color-6 :background ,color-2 :inverse-video nil))))
   `(ace-jump-face-foreground                         ((t (:foreground ,color-11 :background ,color-1 :inverse-video nil))))
   ;; anzu
   `(anzu-mode-line                                   ((t (:foreground ,color-12 :weight bold))))
   ;; full-ack
   `(ack-separator                                    ((t (:foreground ,color-13))))
   `(ack-file                                         ((t (:foreground ,color-11))))
   `(ack-line                                         ((t (:foreground ,color-13))))
   `(ack-match                                        ((t (:foreground ,color-11 :background ,color-3 :weight bold))))
   ;; auto-complete
   `(ac-candidate-face                                ((t (:background ,color-8 :foreground ,color-2 :underline nil))))
   `(ac-selection-face                                ((t (:background ,color-7 :foreground ,color-13 :underline nil))))
   `(ac-yasnippet-candidate-face                      ((t (:background ,color-8 :foreground ,color-3))))
   `(ac-yasnippet-selection-face                      ((t (:background ,color-7 :foreground ,color-12))))
   `(ac-slime-menu-face                               ((t (:background ,color-8 :foreground ,color-1))))
   `(ac-slime-selection-face                          ((t (:background ,color-7 :foreground ,color-12))))
   `(ac-gtags-candidate-face                          ((t (:background ,color-8 :foreground ,color-1))))
   `(ac-gtags-selection-face                          ((t (:background ,color-7 :foreground ,color-12))))
   `(ac-emmet-candidate-face                          ((t (:background ,color-8 :foreground ,color-2))))
   `(ac-emmet-selection-face                          ((t (:background ,color-7 :foreground ,color-12))))

   `(popup-tip-face                                   ((t (:background ,color-11 :foreground ,color-2))))
   `(popup-scroll-bar-foreground-face                 ((t (:background ,color-6))))
   `(popup-scroll-bar-background-face                 ((t (:background ,color-3))))
   `(popup-isearch-match                              ((t (:background ,color-4 :foreground ,color-13))))
   ;; clojure-test-mode
   `(clojure-test-failure-face                        ((t (:foreground ,color-11 :weight bold :underline t))))
   `(clojure-test-error-face                          ((t (:foreground ,color-10 :weight bold :underline t))))
   `(clojure-test-success-face                        ((t (:foreground ,color-10 :weight bold :underline t))))
   ;; ctable
   `(ctbl:face-cell-select                            ((t (:background ,color-11 :foreground ,color-5))))
   `(ctbl:face-continue-bar                           ((t (:background ,color-4 :foreground ,color-5))))
   `(ctbl:face-row-select                             ((t (:background ,color-12 :foreground ,color-5))))
   ;; diff
   `(diff-added                                       ((,class (:foreground ,color-13 :background nil)) (t (:foreground ,color-8 :background nil))))
   `(diff-changed                                     ((t (:foreground ,color-13))))
   `(diff-removed                                     ((,class (:foreground ,color-10 :background nil)) (t (:foreground ,color-8 :background nil))))
   `(diff-refine-added                                ((t :inherit diff-added :weight bold)))
   `(diff-refine-change                               ((t :inherit diff-changed :weight bold)))
   `(diff-refine-removed                              ((t :inherit diff-removed :weight bold)))
   `(diff-header                                      ((,class (:background ,color-7)) (t (:background ,color-13 :foreground ,color-5))))
   `(diff-file-header                                 ((,class (:background ,color-7 :foreground ,color-13 :bold t)) (t (:background ,color-13 :foreground ,color-5 :bold t))))
   ;; dired
   `(dired-directory                                  ((t (:foreground ,color-14 :bold t))))
   ;; dired+
   `(diredp-display-msg                               ((t (:foreground ,color-11))))
   `(diredp-compressed-file-suffix                    ((t (:foreground ,color-11))))
   `(diredp-date-time                                 ((t (:foreground ,color-10))))
   `(diredp-deletion                                  ((t (:foreground ,color-13))))
   `(diredp-deletion-file-name                        ((t (:foreground ,color-10))))
   `(diredp-dir-heading                               ((t (:foreground ,color-13 :background ,color-3 :bold t))))
   `(diredp-dir-priv                                  ((t (:foreground ,color-14 :bold t))))
   `(diredp-dir-name                                  ((t (:foreground ,color-14 :bold t))))
   `(diredp-exec-priv                                 ((t (:foreground ,color-10))))
   `(diredp-executable-tag                            ((t (:foreground ,color-10))))
   `(diredp-file-name                                 ((t (:foreground ,color-11))))
   `(diredp-file-suffix                               ((t (:foreground ,color-11 :bold t))))
   `(diredp-flag-mark                                 ((t (:foreground ,color-13))))
   `(diredp-flag-mark-line                            ((t (:foreground ,color-11))))
   `(diredp-ignored-file-name                         ((t (:foreground ,color-6))))
   `(diredp-link-priv                                 ((t (:foreground ,color-13))))
   `(diredp-mode-line-flagged                         ((t (:foreground ,color-13))))
   `(diredp-mode-line-marked                          ((t (:foreground ,color-11))))
   `(diredp-no-priv                                   ((t (:foreground ,color-13))))
   `(diredp-number                                    ((t (:foreground ,color-10))))
   `(diredp-other-priv                                ((t (:foreground ,color-12))))
   `(diredp-rare-priv                                 ((t (:foreground ,color-9))))
   `(diredp-read-priv                                 ((t (:foreground ,color-8))))
   `(diredp-symlink                                   ((t (:foreground ,color-13))))
   `(diredp-write-priv                                ((t (:foreground ,color-10))))
   ;; ediff
   `(ediff-current-diff-A                             ((t (:foreground ,color-13 :background ,color-7))))
   `(ediff-current-diff-Ancestor                      ((t (:foreground ,color-13 :background ,color-7))))
   `(ediff-current-diff-B                             ((t (:foreground ,color-13 :background ,color-8))))
   `(ediff-current-diff-C                             ((t (:foreground ,color-13 :background ,color-6))))
   `(ediff-even-diff-A                                ((t (:background ,color-6))))
   `(ediff-even-diff-Ancestor                         ((t (:background ,color-6))))
   `(ediff-even-diff-B                                ((t (:background ,color-6))))
   `(ediff-even-diff-C                                ((t (:background ,color-6))))
   `(ediff-fine-diff-A                                ((t (:foreground ,color-13 :background ,color-9 :weight bold))))
   `(ediff-fine-diff-Ancestor                         ((t (:foreground ,color-13 :background ,color-9 weight bold))))
   `(ediff-fine-diff-B                                ((t (:foreground ,color-13 :background ,color-9 :weight bold))))
   `(ediff-fine-diff-C                                ((t (:foreground ,color-13 :background ,color-8 :weight bold ))))
   `(ediff-odd-diff-A                                 ((t (:background ,color-7))))
   `(ediff-odd-diff-Ancestor                          ((t (:background ,color-7))))
   `(ediff-odd-diff-B                                 ((t (:background ,color-7))))
   `(ediff-odd-diff-C                                 ((t (:background ,color-7))))
   ;; eshell
   `(eshell-prompt                                    ((t (:foreground ,color-13 :weight bold))))
   `(eshell-ls-archive                                ((t (:foreground ,color-9 :weight bold))))
   `(eshell-ls-backup                                 ((t (:inherit font-lock-comment-face))))
   `(eshell-ls-clutter                                ((t (:inherit font-lock-comment-face))))
   `(eshell-ls-directory                              ((t (:foreground ,color-11 :weight bold))))
   `(eshell-ls-executable                             ((t (:foreground ,color-11 :weight bold))))
   `(eshell-ls-unreadable                             ((t (:foreground ,color-13))))
   `(eshell-ls-missing                                ((t (:inherit font-lock-warning-face))))
   `(eshell-ls-product                                ((t (:inherit font-lock-doc-face))))
   `(eshell-ls-special                                ((t (:foreground ,color-13 :weight bold))))
   `(eshell-ls-symlink                                ((t (:foreground ,color-12 :weight bold))))
   ;; flx
   `(flx-highlight-face                               ((t (:foreground ,color-11 :weight bold))))
   ;; flycheck
   `(flycheck-error                                   ((((supports :underline (:style wave))) (:underline (:style wave :color ,color-7) :inherit unspecified)) (t (:foreground ,color-13 :weight bold :underline t))))
   `(flycheck-warning                                 ((((supports :underline (:style wave))) (:underline (:style wave :color ,color-6) :inherit unspecified)) (t (:foreground ,color-11 :weight bold :underline t))))
   `(flycheck-info                                    ((((supports :underline (:style wave))) (:underline (:style wave :color ,color-5) :inherit unspecified)) (t (:foreground ,color-10 :weight bold :underline t))))
   `(flycheck-fringe-error                            ((t (:foreground ,color-1 :weight bold))))
   `(flycheck-fringe-warning                          ((t (:foreground ,color-4 :weight bold))))
   `(flycheck-fringe-info                             ((t (:foreground ,color-4 :weight bold))))
   ;; flymake
   `(flymake-errline                                  ((((supports :underline (:style wave))) (:underline (:style wave :color ,color-10) :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground ,color-9 :weight bold :underline t))))
   `(flymake-warnline                                 ((((supports :underline (:style wave))) (:underline (:style wave :color ,color-11) :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground ,color-11 :weight bold :underline t))))
   `(flymake-infoline                                 ((((supports :underline (:style wave))) (:underline (:style wave :color ,color-9) :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground ,color-8 :weight bold :underline t))))
   ;; flyspell
   `(flyspell-duplicate                               ((((supports :underline (:style wave))) (:underline (:style wave :color ,color-11) :inherit unspecified)) (t (:foreground ,color-11 :weight bold :underline t))))
   `(flyspell-incorrect                               ((((supports :underline (:style wave))) (:underline (:style wave :color ,color-10) :inherit unspecified)) (t (:foreground ,color-9 :weight bold :underline t))))
   ;; erc
   `(erc-action-face                                  ((t (:inherit erc-default-face))))
   `(erc-bold-face                                    ((t (:weight bold))))
   `(erc-current-nick-face                            ((t (:foreground ,color-11 :weight bold))))
   `(erc-dangerous-host-face                          ((t (:inherit font-lock-warning-face))))
   `(erc-default-face                                 ((t (:foreground ,color-13))))
   `(erc-direct-msg-face                              ((t (:inherit erc-default))))
   `(erc-error-face                                   ((t (:inherit font-lock-warning-face))))
   `(erc-fool-face                                    ((t (:inherit erc-default))))
   `(erc-highlight-face                               ((t (:inherit hover-highlight))))
   `(erc-input-face                                   ((t (:foreground ,color-13))))
   `(erc-keyword-face                                 ((t (:foreground ,color-11 :weight bold))))
   `(erc-nick-default-face                            ((t (:foreground ,color-13 :weight bold))))
   `(erc-my-nick-face                                 ((t (:foreground ,color-10 :weight bold))))
   `(erc-nick-msg-face                                ((t (:inherit erc-default))))
   `(erc-notice-face                                  ((t (:foreground ,color-9))))
   `(erc-pal-face                                     ((t (:foreground ,color-11 :weight bold))))
   `(erc-prompt-face                                  ((t (:foreground ,color-11 :background ,color-4 :weight bold))))
   `(erc-timestamp-face                               ((t (:foreground ,color-13))))
   `(erc-underline-face                               ((t (:underline t))))
   ;; git-gutter
   `(git-gutter:added                                 ((t (:background ,color-4 :foreground ,color-1 :weight bold ))))
   `(git-gutter:deleted                               ((t (:background ,color-4 :foreground ,color-1 :weight bold ))))
   `(git-gutter:modified                              ((t (:background ,color-4 :foreground ,color-1 :weight bold ))))
   `(git-gutter:unchanged                             ((t (:background ,color-4 :foreground ,color-1 :weight bold ))))
   ;; git-gutter-fr
   `(git-gutter-fr:added                              ((t (:foreground ,color-2 :weight bold))))
   `(git-gutter-fr:deleted                            ((t (:foreground ,color-2 :weight bold))))
   `(git-gutter-fr:modified                           ((t (:foreground ,color-2 :weight bold))))
   ;; guide-key
   `(guide-key/highlight-command-face                 ((t (:foreground ,color-11))))
   `(guide-key/key-face                               ((t (:foreground ,color-9))))
   `(guide-key/prefix-command-face                    ((t (:foreground ,color-10))))
   ;; helm
   `(helm-header                                      ((t (:foreground ,color-9 :background ,color-4 :underline nil :box nil))))
   `(helm-source-header                               ((t (:foreground ,color-13 :background ,color-3 :underline nil :weight bold :box (:line-width -1 :style released-button)))))
   `(helm-selection                                   ((t (:background ,color-6 :underline nil))))
   `(helm-selection-line                              ((t (:background ,color-6))))
   `(helm-visible-mark                                ((t (:foreground ,color-5 :background ,color-11))))
   `(helm-candidate-number                            ((t (:foreground ,color-13 :background ,color-3))))
   `(helm-separator                                   ((t (:foreground ,color-10 :background ,color-4))))
   `(helm-time-zone-current                           ((t (:foreground ,color-11 :background ,color-4))))
   `(helm-time-zone-home                              ((t (:foreground ,color-10 :background ,color-4))))
   `(helm-bookmark-addressbook                        ((t (:foreground ,color-11 :background ,color-4))))
   `(helm-bookmark-directory                          ((t (:foreground nil :background nil :inherit helm-ff-directory))))
   `(helm-bookmark-file                               ((t (:foreground nil :background nil :inherit helm-ff-file))))
   `(helm-bookmark-gnus                               ((t (:foreground ,color-10 :background ,color-4))))
   `(helm-bookmark-info                               ((t (:foreground ,color-11 :background ,color-4))))
   `(helm-bookmark-man                                ((t (:foreground ,color-13 :background ,color-4))))
   `(helm-bookmark-w3m                                ((t (:foreground ,color-10 :background ,color-4))))
   `(helm-buffer-not-saved                            ((t (:foreground ,color-10 :background ,color-4))))
   `(helm-buffer-process                              ((t (:foreground ,color-12 :background ,color-4))))
   `(helm-buffer-saved-out                            ((t (:foreground ,color-13 :background ,color-4))))
   `(helm-buffer-size                                 ((t (:foreground ,color-7 :background ,color-4))))
   `(helm-buffer-directory                            ((t (:foreground ,color-10 :background ,color-4))))
   `(helm-lisp-completion-info                        ((t (:foreground ,color-10 :background ,color-4))))
   `(helm-lisp-show-completion                        ((t (:foreground ,color-12 :background ,color-6))))
   `(helm-locate-finish                               ((t (:foreground ,color-8 :background ,color-4))))
   `(helm-dotted-symlink-directory                    ((t (:foreground ,color-7 :background ,color-5))))
   `(helm-ff-dotted-symlink-directory                 ((t (:foreground ,color-7 :background ,color-5))))
   `(helm-ff-directory                                ((t (:foreground ,color-12 :background ,color-4 :weight bold))))
   `(helm-ff-file                                     ((t (:foreground ,color-13 :background ,color-4 :weight normal))))
   `(helm-ff-executable                               ((t (:foreground ,color-11 :background ,color-4 :weight normal))))
   `(helm-ff-invalid-symlink                          ((t (:foreground ,color-10 :background ,color-4 :weight bold))))
   `(helm-ff-symlink                                  ((t (:foreground ,color-13 :background ,color-4 :weight bold))))
   `(helm-ff-prefix                                   ((t (:foreground ,color-5 :background ,color-13 :weight normal))))
   `(helm-grep-cmd-line                               ((t (:foreground ,color-12 :background ,color-4))))
   `(helm-grep-file                                   ((t (:foreground ,color-13 :background ,color-4))))
   `(helm-grep-finish                                 ((t (:foreground ,color-11 :background ,color-4))))
   `(helm-grep-lineno                                 ((t (:foreground ,color-7 :background ,color-4))))
   `(helm-match                                       ((t (:foreground ,color-12 :background ,color-5))))
   `(helm-grep-match                                  ((t ( :inherit helm-match))))
   `(helm-grep-running                                ((t (:foreground ,color-10 :background ,color-4))))
   `(helm-moccur-buffer                               ((t (:foreground ,color-12 :background ,color-4))))
   `(helm-mu-contacts-address-face                    ((t (:foreground ,color-7 :background ,color-4))))
   `(helm-mu-contacts-name-face                       ((t (:foreground ,color-13 :background ,color-4))))
   `(helm-M-x-key                                     ((t (:foreground ,color-12 :background ,color-4 :weight bold))))
   ;; hl-line-mode
   `(hl-line-face                                     ((,class (:background ,color-3)) (t :weight bold)))
   `(hl-line                                          ((,class (:background ,color-3)) (t :weight bold)))
   ;; hl-sexp
   `(hl-sexp-face                                     ((,class (:background ,color-6)) (t :weight bold)))
   ;; ido-mode
   `(ido-first-match                                  ((t (:foreground ,color-13 :weight bold))))
   `(ido-only-match                                   ((t (:foreground ,color-11 :weight bold))))
   `(ido-subdir                                       ((t (:foreground ,color-13))))
   `(ido-indicator                                    ((t (:foreground ,color-13 :background ,color-7))))
   ;; iedit-mode
   `(iedit-occurrence                                 ((t (:background ,color-7 :weight bold))))
   ;; js2-mode

   `(js2-warning                                      ((t (:underline ,color-3))))
   `(js2-error                                        ((t (:foreground ,color-10 :weight bold))))
   `(js2-jsdoc-tag                                    ((t (:foreground ,color-8))))
   `(js2-jsdoc-type                                   ((t (:foreground ,color-11))))
   `(js2-jsdoc-value                                  ((t (:foreground ,color-12))))
   `(js2-jsdoc-html-tag-name                          ((t (:foreground ,color-11))))
   `(js2-jsdoc-html-tag-delimiter                     ((t (:foreground ,color-12))))
   `(js2-function-param                               ((t (:foreground, color-12))))
   `(js2-function-call                                ((t (:foreground, color-12 :underline t))))
   `(js2-object-property                              ((t (:foreground, color-12  :slant italic))))
   `(js2-external-variable                            ((t (:foreground ,color-7))))

   ;; jabber-mode
   `(jabber-roster-user-away                          ((t (:foreground ,color-11))))
   `(jabber-roster-user-online                        ((t (:foreground ,color-10))))
   `(jabber-roster-user-dnd                           ((t (:foreground ,color-11))))
   `(jabber-rare-time-face                            ((t (:foreground ,color-10))))
   `(jabber-chat-prompt-local                         ((t (:foreground ,color-10))))
   `(jabber-chat-prompt-foreign                       ((t (:foreground ,color-11))))
   `(jabber-activity-face                             ((t (:foreground ,color-11))))
   `(jabber-activity-personal-face                    ((t (:foreground ,color-11))))
   `(jabber-title-small                               ((t (:height 1.1 :weight bold))))
   `(jabber-title-medium                              ((t (:height 1.2 :weight bold))))
   `(jabber-title-large                               ((t (:height 1.3 :weight bold))))
   ;; linum-mode
   `(linum                                            ((t (:foreground ,color-11 :background ,color-4))))
   ;; magit
   `(magit-section-title                              ((t (:foreground ,color-13 :weight bold))))
   `(magit-branch                                     ((t (:foreground ,color-11 :weight bold))))
   `(magit-item-highlight                             ((t (:background ,color-6 :bold nil))))
   ;; message-mode
   `(message-cited-text                               ((t (:inherit font-lock-comment-face))))
   `(message-header-name                              ((t (:foreground ,color-10))))
   `(message-header-other                             ((t (:foreground ,color-9))))
   `(message-header-to                                ((t (:foreground ,color-13 :weight bold))))
   `(message-header-from                              ((t (:foreground ,color-13 :weight bold))))
   `(message-header-cc                                ((t (:foreground ,color-13 :weight bold))))
   `(message-header-newsgroups                        ((t (:foreground ,color-13 :weight bold))))
   `(message-header-subject                           ((t (:foreground ,color-11 :weight bold))))
   `(message-header-xheader                           ((t (:foreground ,color-9))))
   `(message-mml                                      ((t (:foreground ,color-13 :weight bold))))
   `(message-separator                                ((t (:inherit font-lock-comment-face))))
   ;; mic-paren
   `(paren-face-match                                 ((t (:foreground ,color-12 :background ,color-3 ))))
   `(paren-face-mismatch                              ((t (:foreground ,color-2 :background ,color-3 ))))
   `(paren-face-no-match                              ((t (:foreground ,color-6 :background ,color-3 ))))
   ;; mu4e
   `(mu4e-cited-1-face                                ((t (:foreground ,color-11    :slant italic))))
   `(mu4e-cited-2-face                                ((t (:foreground ,color-11 :slant italic))))
   `(mu4e-cited-3-face                                ((t (:foreground ,color-9  :slant italic))))
   `(mu4e-cited-4-face                                ((t (:foreground ,color-9   :slant italic))))
   `(mu4e-cited-5-face                                ((t (:foreground ,color-7  :slant italic))))
   `(mu4e-cited-6-face                                ((t (:foreground ,color-8 :slant italic))))
   `(mu4e-cited-7-face                                ((t (:foreground ,color-11    :slant italic))))
   `(mu4e-replied-face                                ((t (:foreground ,color-8))))
   `(mu4e-trashed-face                                ((t (:foreground ,color-8 :strike-through t))))
   ;; org-mode
   `(org-agenda-date-today                            ((t (:foreground ,color-14 :slant italic :weight bold))) t)
   `(org-agenda-structure                             ((t (:inherit font-lock-comment-face))))
   `(org-archived                                     ((t (:foreground ,color-13 :weight bold))))
   `(org-checkbox                                     ((t (:background ,color-7 :foreground ,color-14 :box (:line-width 1 :style released-button)))))
   `(org-date                                         ((t (:foreground ,color-11 :underline t))))
   `(org-deadline-announce                            ((t (:foreground ,color-9))))
   `(org-formula                                      ((t (:foreground ,color-11))))
   `(org-headline-done                                ((t (:foreground ,color-12))))
   `(org-hide                                         ((t (:foreground ,color-3))))
   `(org-document-title                               ((t (:foreground "#517FA6" :bold t))))
   `(org-level-1                                      ((t (:foreground "#517FA6" :bold t))))
   `(org-level-2                                      ((t (:foreground ,color-10 :bold t))))
   `(org-level-3                                      ((t (:foreground ,color-9))))
   `(org-level-4                                      ((t (:foreground ,color-9 :height 1.0))))
   `(org-level-5                                      ((t (:foreground ,color-9 :height 1.0))))
   `(org-level-6                                      ((t (:foreground ,color-9 :height 1.0))))
   `(org-level-7                                      ((t (:foreground ,color-9 :height 1.0))))
   `(org-level-8                                      ((t (:foreground ,color-8 :height 1.0))))
   `(org-link                                         ((t (:foreground ,color-11 :underline t))))
   `(org-scheduled                                    ((t (:foreground ,color-13))))
   `(org-scheduled-previously                         ((t (:foreground ,color-10))))
   `(org-scheduled-today                              ((t (:foreground ,color-11))))
   `(org-sexp-date                                    ((t (:foreground ,color-11 :underline t))))
   `(org-special-keyword                              ((t (:inherit font-lock-comment-face))))
   `(org-table                                        ((t (:foreground ,color-11))))
   `(org-tag                                          ((t (:foreground "darkcyan"))))
   `(org-time-grid                                    ((t (:foreground ,color-11))))
   `(org-done                                         ((t (:bold t :foreground "green"))))
   `(org-todo                                         ((t (:bold t :foreground "red"))))
   `(org-upcoming-deadline                            ((t (:inherit font-lock-keyword-face))))
   `(org-warning                                      ((t (:bold t :foreground ,color-10 :weight bold :underline nil))))
   `(org-column                                       ((t (:background ,color-3))))
   `(org-column-title                                 ((t (:background ,color-3 :underline t :weight bold))))
   `(org-mode-line-clock                              ((t (:foreground ,color-13 :background ,color-3))))
   `(org-mode-line-clock-overrun                      ((t (:foreground ,color-5 :background ,color-9))))
   `(org-ellipsis                                     ((t (:foreground ,color-12 :underline t))))
   `(org-footnote                                     ((t (:foreground ,color-12 :underline t))))
   `(org-meta-line                                    ((t (:foreground ,color-8 :height 1.0))))
   `(org-block-background                             ((t (:background ,color-4 :height 1.0))))
   `(org-block                                        ((t (:foreground ,color-7 :height 1.0))))

   ;; outline
   `(outline-1                                        ((t (:foreground ,color-11))))
   `(outline-2                                        ((t (:foreground ,color-13))))
   `(outline-3                                        ((t (:foreground ,color-10))))
   `(outline-4                                        ((t (:foreground ,color-11))))
   `(outline-5                                        ((t (:foreground ,color-12))))
   `(outline-6                                        ((t (:foreground ,color-11))))
   `(outline-7                                        ((t (:foreground ,color-7))))
   `(outline-8                                        ((t (:foreground ,color-7))))
   ;; perspective
   `(persp-selected-face                              ((t (:foreground "springreen3"))))
   ;; rainbow-delimiters
   `(rainbow-delimiters-depth-1-face                  ((t (:foreground "gray35"))))
   `(rainbow-delimiters-depth-2-face                  ((t (:foreground "gray35"))))
   `(rainbow-delimiters-depth-3-face                  ((t (:foreground "gray35"))))
   `(rainbow-delimiters-depth-4-face                  ((t (:foreground "gray35"))))
   `(rainbow-delimiters-depth-5-face                  ((t (:foreground "gray35"))))
   `(rainbow-delimiters-depth-6-face                  ((t (:foreground "gray35"))))
   `(rainbow-delimiters-depth-7-face                  ((t (:foreground "gray35"))))
   `(rainbow-delimiters-depth-8-face                  ((t (:foreground "gray35"))))
   `(rainbow-delimiters-depth-9-face                  ((t (:foreground "gray35"))))
   `(rainbow-delimiters-depth-10-face                 ((t (:foreground "gray35"))))
   `(rainbow-delimiters-depth-11-face                 ((t (:foreground "gray35"))))
   `(rainbow-delimiters-depth-12-face                 ((t (:foreground "gray35"))))
   ;; sh-mode
   `(sh-heredoc                                       ((t (:foreground ,color-13 :bold t))))
   `(sh-quoted-exec                                   ((t (:foreground ,color-10))))
   ;; show-paren
   `(show-paren-mismatch                         ((t (:foreground ,color-1 :background ,color-7 :weight bold))))
   `(show-paren-match                            ((t (:foreground ,color-11 :background ,color-3  :weight bold))))
   ;; smartparens
   `(sp-show-pair-mismatch-face                       ((t (:foreground ,color-14 :background ,color-3))))
   `(sp-show-pair-match-face                          ((t (:foreground ,color-14 :background ,color-6 :underline nil))))
   ;; sml-mode-line
   '(sml-modeline-end-face                            ((t :inherit default :width condensed)))
   ;; SLIME
   `(slime-repl-output-face                           ((t (:foreground ,color-10))))
   `(slime-repl-inputed-output-face                   ((t (:foreground ,color-9))))
   `(slime-error-face                                 ((((supports :underline (:style wave))) (:underline (:style wave :color ,color-10))) (t (:underline ,color-10))))
   `(slime-warning-face                               ((((supports :underline (:style wave))) (:underline (:style wave :color ,color-11))) (t (:underline ,color-11))))
   `(slime-style-warning-face                         ((((supports :underline (:style wave))) (:underline (:style wave :color ,color-13))) (t (:underline ,color-13))))
   `(slime-note-face                                  ((((supports :underline (:style wave))) (:underline (:style wave :color ,color-9))) (t (:underline ,color-9))))
   `(slime-highlight-face                             ((t (:inherit highlight))))
   ;; tabbar
   `(tabbar-button                                    ((t (:foreground ,color-13 :background ,color-4))))
   `(tabbar-selected                                  ((t (:foreground ,color-13 :background ,color-4 :box (:line-width -1 :style pressed-button)))))
   `(tabbar-unselected                                ((t (:foreground ,color-13 :background ,color-6 :box (:line-width -1 :style released-button)))))
   ;; term
   `(term-color-black                                 ((t (:foreground ,color-5 :background ,color-3))))
   `(term-color-red                                   ((t (:foreground ,color-9 :background ,color-7))))
   `(term-color-green                                 ((t (:foreground ,color-9 :background ,color-11))))
   `(term-color-yellow                                ((t (:foreground ,color-11 :background ,color-13))))
   `(term-color-blue                                  ((t (:foreground ,color-10 :background ,color-7))))
   `(term-color-magenta                               ((t (:foreground ,color-10 :background ,color-10))))
   `(term-color-cyan                                  ((t (:foreground ,color-12 :background ,color-11))))
   `(term-color-white                                 ((t (:foreground ,color-13 :background ,color-7))))
   '(term-default-fg-color                            ((t (:inherit term-color-white))))
   '(term-default-bg-color                            ((t (:inherit term-color-black))))
   ;; undo-tree
   `(undo-tree-visualizer-active-branch-face          ((t (:foreground ,color-14 :weight bold))))
   `(undo-tree-visualizer-current-face                ((t (:foreground ,color-9 :weight bold))))
   `(undo-tree-visualizer-default-face                ((t (:foreground ,color-13))))
   `(undo-tree-visualizer-register-face               ((t (:foreground ,color-13))))
   `(undo-tree-visualizer-unmodified-face             ((t (:foreground ,color-12))))
   ;; volatile-highlights
   `(vhl/default-face                                 ((t (:background ,color-4))))
   ;; whitespace-mode
   `(whitespace-space                                 ((t (:background ,color-6 :foreground ,color-6))))
   `(whitespace-hspace                                ((t (:background ,color-6 :foreground ,color-6))))
   `(whitespace-tab                                   ((t (:background ,color-9))))
   `(whitespace-newline                               ((t (:foreground ,color-6))))
   `(whitespace-trailing                              ((t (:background ,color-10))))
   `(whitespace-line                                  ((t (:background ,color-4 :foreground ,color-10))))
   `(whitespace-space-before-tab                      ((t (:background ,color-11 :foreground ,color-11))))
   `(whitespace-indentation                           ((t (:background ,color-13 :foreground ,color-10))))
   `(whitespace-empty                                 ((t (:background ,color-13))))
   `(whitespace-space-after-tab                       ((t (:background ,color-13 :foreground ,color-10))))
   ;; which-func-mode
   `(which-func                                       ((t (:foreground ,color-13))))
   `(minimap-active-region-background                 ((t (:background ,color-6 :foreground ,color-7))))
   ;; html fold/unfold face
   `(html-fold-unfolded-face                          ((t (:background ,color-4))))
   `(html-fold-folded-face                            ((t (:foreground ,color-14 :bold t))))
   ;; markdown mode
   `(markdown-header-delimiter-face                   ((t (:weight normal :foreground ,color-6))))
   `(markdown-header-face-1                           ((t (:inherit markdown-header-face :height 1.5))))
   `(markdown-header-face-2                           ((t (:inherit markdown-header-face :height 1.3))))
   `(markdown-header-face-3                           ((t (:inherit markdown-header-face :underline t :height 1.2))))
   `(markdown-header-face-4                           ((t (:inherit markdown-header-face :underline t :height 1.1))))
   `(markdown-header-face-5                           ((t (:inherit markdown-header-face :underline t))))
   `(markdown-header-face-6                           ((t (:inherit markdown-header-face :underline t))))
   `(markdown-link-face                               ((t (:underline t :foreground ,color-13))))
   `(markdown-url-face                                ((t (:underline t :foreground ,color-12))))
   `(markdown-pre-face                                ((t (:foreground ,color-13 :height .8 ))))
   `(markdown-bold-face                                ((t (:foreground ,color-8 :bold t ))))
   `(markdown-italic-face                                ((t (:foreground ,color-8 :italic t ))))
   `(markdown-list-face                               ((t (:foreground ,color-12))))
   `(markdown-markup-face                             ((t (:foreground ,color-6 ))))
   ;; swoop
   `(swoop-face-line-buffer-name                      ((t (:background ,color-9 :foreground ,color-1))))
   `(swoop-face-target-line                           ((t (:background ,color-7 :foreground ,color-12))))
   `(swoop-face-line-number                           ((t (:background ,color-4 :foreground ,color-6))))
   `(swoop-face-header-format-line                    ((t (:background ,color-6 :foreground ,color-1))))
   `(swoop-face-target-words                          ((t (:background ,color-6 :foreground ,color-13))))
   `(highlight-indentation-face                       ((t (:background ,color-5))))
   `(highlight-indentation-current-column-face        ((t (:background ,color-3))))
   `(comint-highlight-prompt ((t (:foreground "#517FA6" :bold t))))
   ;; company
   `(company-echo-common                              ((t (:foreground ,color-13))))
   `(company-preview                                  ((t (:background ,color-6 :foreground ,color-11))))
   `(company-preview-common                           ((t (:inherit company-preview :foreground ,color-13 :weight bold))))
   `(company-scrollbar-fg                             ((t (:background ,color-7))))
   `(company-tooltip                                  ((t (:background ,color-6 :foreground ,color-11))))
   `(company-tooltip-annotation                       ((t (:inherit company-tooltip :foreground ,color-2))))
   `(company-tooltip-common                           ((t (:inherit company-tooltip :foreground ,color-11))))
   `(company-tooltip-common-selection                 ((t (:inherit company-tooltip-selection :foreground ,color-13))))
   `(company-tooltip-selection                        ((t (:inherit company-tooltip :background ,color-8 :foreground ,color-1))))
   `(company-scrollbar-bg                             ((t (:inherit company-tooltip))))
   ;; eval-sexp-fu
   `(eval-sexp-fu-flash                               ((t (:background ,color-5))))
   `(eval-sexp-fu-flash-error                         ((t (:background ,color-11 :foreground ,color-1))))
   `(compilation-error                                ((t (:foreground ,color-12 :underline t :bold t))))

   ;; tuareg
   `(tuareg-font-lock-operator-face                   ((t (:inherit ,font-lock-variable-name-face))))
   `(tuareg-font-lock-governing-face                  ((t (:inherit ,font-lock-keyword-face))))
   ;; avy
   `(avy-lead-face                                    ((t (:background ,color-8 :foreground ,color-1 :bold t))))
   `(avy-lead-face-0                                  ((t (:background ,color-9  :foreground ,color-1  :bold t))))
   `(avy-lead-face-1                                  ((t (:background ,color-10  :foreground ,color-1 :bold t))))
   `(avy-lead-face-2                                  ((t (:background ,color-11  :foreground ,color-1 :bold t))))
   `(avy-background-face                              ((t (:background ,color-3  :foreground ,color-7 :bold t))))
   )

  ;; Theme Variables
  (custom-theme-set-variables
   theme-name
   ;; ansi-color
   `(ansi-color-names-vector [,color-5
                              ,color-10
                              ,color-9
                              ,color-13
                              ,color-11
                              ,color-10
                              ,color-12
                              ,color-13])
   ;; fill-column-indicator
   `(fci-rule-color ,color-4)
   ;; vc-annotate
   `(vc-annotate-color-map
     '(( 20. . ,color-7)
       ( 40. . ,color-8)
       ( 60. . ,color-8)
       ( 80. . ,color-9)
       (100. . ,color-9)
       (120. . ,color-10)
       (140. . ,color-10)
       (160. . ,color-11)
       (180. . ,color-11)
       (200. . ,color-11)
       (220. . ,color-12)
       (240. . ,color-12)
       (260. . ,color-12)
       (280. . ,color-13)
       (300. . ,color-13)
       (320. . ,color-13)
       (340. . ,color-14)
       (360. . ,color-14)))
   `(vc-annotate-very-old-color ,color-10)
   `(vc-annotate-background ,color-3)
   ))

(provide 'tao-yinyang-common)
